## *Jeu de données IRVE*
-------------------
# Analyse des relations entre champs (intégrité des données)
------------------------------
## Contexte
- clarification du rôle des modèles de données dans les jeux de données (cf mise à jour récente des [guides data.gouv](https://guides.etalab.gouv.fr/qualite/documenter-les-donnees/))
- intégration d'une propriété "relationship" dans les schémas de données ([issue TableSchema](https://github.com/frictionlessdata/specs/issues/803) en cours de validation)
- création d'outils de contrôle des relations entre champs des jeux de données tabulaires (cf usage ci-dessous)

## Objectifs
- valider sur un cas réel l'utilisation d'un modèle de données en complément d'un schéma de données
- identifier les apports que pourraient avoir les contrôles de validation des relations entre champs

## Résultats
- les principaux résultats sont regroupés sur un [tableau de bord](https://nbviewer.org/github/loco-philippe/Environmental-Sensing/blob/main/python/Validation/irve/Analyse/IRVE_indicateurs.ipynb) 
- la formalisation d'un modèle de données facilite la compréhension des données et des relations entre champs
- l'outil de contrôle permet d'améliorer significativement la qualité des données par l'identification d'incohérences de relations
- l'identification des incohérences permet de trouver des stratégies de réduction des écarts (dans l'exemple ci-dessous, on passe 36% d'écart à 3,8 %)  
- l'analyse des données permet de (re)construire le modèle de données qui minimise les incohérences
- les incohérences détectées sur le jeu de données IRVE restent faibles (inférieures à 5 % des point de charge documentés - voir chapitre 4)

## Suite à donner
- Mettre à jour, valider et publier le modèle de données IRVE
- Définir les contrôles supplémentaires à intégrer pour toutes nouvelles données ainsi que pour le jeu complet
- Mettre en oeuvre les outils de contrôle

## Evolutions possibles 
- Ajouter dans les guides d'Etalab un guide pour les modèles de données 
- Intégrer dans les schémas de données la propriété "relationship" en cours de validation,
- Définir un indicateur qui mesure l'écart (existant / attendu) des relations entre champs

## Sommaire
*(liens actifs sur jupyter Notebook ou Nbviewer)*
- [1 - modèle de données](#1---modèle-de-données)
- [2 - Initialisation](#2---Initialisation)
- [3 - Séparation des pdc itinerance et hors itinerance](#3---Séparation-des-pdc-itinerance-et-hors-itinerance)
- [4 - Bilan initial intégrité](#4---Bilan-initial-intégrité)
- [5 - Séparation doublons pdc - date de maj](#5---Séparation-doublons-pdc---date-de-maj)
- [6 - Séparation doublons station - date de maj](#6---Séparation-doublons-station---date-de-maj)
- [7 - Synthèse](#7---Synthèse)
- [8 - Exemples d'erreurs résiduelles](#8---Exemples-d\'erreurs-résiduelles)

Ce Notebook peut être consulté sur [nbviewer](http://nbviewer.org/github/loco-philippe/Environmental-Sensing/tree/main/python/Validation/irve/Analyse)

données utilisées : https://www.data.gouv.fr/fr/datasets/fichier-consolide-des-bornes-de-recharge-pour-vehicules-electriques/    
fichier : "*consolidation-etalab-schema-irve-statique-v-2.2.0-2024xxxx.csv*"

-----------------------
# 1 - modèle de données

Le modèle de données proposé ci-dessous est construit sur la base du schéma de données mis à disposition et du contenu du jeu de données.    
Il est à consolider en fonction de l'expertise des concepteurs et réutilisateurs (voir [guide méthodologique](https://github.com/loco-philippe/Environmental-Sensing/blob/main/property_relationship/FR_methodology.ipynb)).

*Notation:*
- *M : Mandatory - documentation obligatoire*
- *PK : Primary Key - identifiant unique de l'entité*
- *Root : champ fictif associé à une ligne du tableau*

In [2]:
from base64 import b64encode

from IPython.display import Image, display

with open("IRVE_modele.txt", "r", encoding="utf-8") as f:
    modele = f.read()
display(
    Image(
        url="https://mermaid.ink/img/"
        + b64encode(modele.encode("ascii")).decode("ascii")
    )
)

------
# 2 - Initialisation
## initialisation logicielle

In [36]:
import json
import pathlib
from datetime import datetime

import ntv_pandas as npd
import pandas as pd
from pandas import NamedAgg
from tab_dataset import Cdataset


def analyse_integrite(data, schema, affiche=True, indic=True):
    """analyse les relations du DataFrame 'data' définies dans le schéma 'schema'.
    Le nombre de ligne en erreur par relation (dict) est retourné et optionnellement affiché (paramètre 'affiche=True') .
    Les lignes en erreur sont optionnellement ajoutées (paramètre 'indic=True') à 'data' sous forme de champs booléens par relation.
    """
    dic_errors = Cdataset(data).check_relationship(schema)
    dic_count = {name: len(errors) for name, errors in dic_errors.items()}
    if affiche:
        for name, total in dic_count.items():
            print(f"{name:<50} {total:>5}")
    if indic:
        data["ok"] = True
        for name, errors in dic_errors.items():
            data[name] = True
            data.loc[errors, name] = False
            data["ok"] = data["ok"] & data[name]
    return dic_count


def add_nbre_pdc(data, affiche=True):
    """ajoute un champ avec le nombre de pdc calculés et le compare au champ 'nbre_pdc'
    Le nombre d'écarts est affiché optionnellement (paramètre 'affiche=True').
    """
    data["nb_pdc_calc"] = data.groupby("id_station_itinerance")["index"].transform(
        "count"
    )
    nbre_pdc = data["nbre_pdc"].astype("int")
    data["nbre_pdc_ok"] = data["nb_pdc_calc"] == nbre_pdc
    data["calc-nbre"] = data["nb_pdc_calc"] - nbre_pdc
    if affiche:
        ecart_nbre = len(data) - data["nbre_pdc_ok"].sum()
        print("{:<20} {:>5}".format("nbre_pdc_ko", ecart_nbre))
        print(round(ecart_nbre / len(data) * 100), " %")

## initialisation des données
- lecture du fichier issu de l'api 190 000 lignes (120 000 fin 2024)

In [55]:
dates = [
    "2023-03-03",
    "2023-04-17",
    "2023-05-02",
    "2023-05-24",
    "2023-06-17",
    "2023-07-04",
    "2023-07-23",
    "2023-08-08",
    "2023-09-06",
    "2023-09-19",
    "2023-10-04",
    "2023-10-21",
    "2023-10-31",
    "2023-11-23",
    "2023-12-14",
    "2023-12-29",
    "2024-01-15",
    "2024-02-07",
    "2024-02-28",
    "2024-03-27",
    "2024-04-24",
    "2024-05-19",
    "2024-06-05",
    "2024-08-02",
    "2024-10-24",
    "2024-11-27",
    "2025-01-03",
    "2025-10-04",
    "2025-11-18",
    "2026-02-18",
    "2026-09-29",
]
date = dates[-1]
log = {
    "date_irve": date,
    "file": "consolidation-etalab-schema-irve-statique-v-2.3.1-"
    + date[:4]
    + date[5:7]
    + date[8:]
    + ".csv",  # après 2024-02-06
    "chemin": str(
        pathlib.Path(npd.__file__).parent.parent.parent
        / "Environmental-Sensing"
        / "python"
        / "Validation"
        / "irve"
        / "Analyse"
    ),
}
irve = pd.read_csv(
    log["chemin"] + "/" + log["file"], sep=",", low_memory=False, dtype="object"
)
log["len_irve"] = len(irve)
print("nombre de lignes : ", log["len_irve"])

nombre de lignes :  169404

## schéma de données
Le schéma de données restreint à la propriété 'relationship' et construit à partir du modèle de données est le suivants :

In [53]:
# complément à inclure dans le schéma de données
schema = {
    "relationships": [
        # relation unicité des pdl
        {"fields": ["id_pdc_itinerance", "index"], "link": "coupled"},
        # relations inter entités
        {"fields": ["id_station_itinerance", "contact_operateur"], "link": "derived"},
        {"fields": ["id_station_itinerance", "nom_enseigne"], "link": "derived"},
        {"fields": ["id_station_itinerance", "coordonneesXY"], "link": "derived"},
        {"fields": ["id_pdc_itinerance", "id_station_itinerance"], "link": "derived"},
        # relations intra entité - station
        {"fields": ["id_station_itinerance", "nom_station"], "link": "derived"},
        {
            "fields": ["id_station_itinerance", "implantation_station"],
            "link": "derived",
        },
        # {"fields": ["id_station_itinerance", "date_maj"],             "link" : "derived" },
        {"fields": ["id_station_itinerance", "nbre_pdc"], "link": "derived"},
        {"fields": ["id_station_itinerance", "condition_acces"], "link": "derived"},
        {"fields": ["id_station_itinerance", "horaires"], "link": "derived"},
        {"fields": ["id_station_itinerance", "station_deux_roues"], "link": "derived"},
        # relations intra entité - localisation
        {"fields": ["coordonneesXY", "adresse_station"], "link": "derived"},
    ]
}
# liste des champs liés à un controle (relations) et obligatoires (mandatory)
relations = [
    "index",
    "contact_operateur",
    "nom_enseigne",
    "coordonneesXY",
    "adresse_station",
    "id_station_itinerance",
    "nom_station",
    "implantation_station",
    "nbre_pdc",
    "condition_acces",
    "horaires",
    "station_deux_roues",
    "id_pdc_itinerance",
    "date_maj",
    "last_modified",
    "datagouv_organization_or_owner",
]
mandatory = [
    "contact_operateur",
    "nom_enseigne",
    "coordonneesXY",
    "adresse_station",
    "id_station_itinerance",
    "nom_station",
    "implantation_station",
    "nbre_pdc",
    "condition_acces",
    "horaires",
    "station_deux_roues",
    "id_pdc_itinerance",
    "puissance_nominale",
    "prise_type_ef",
    "prise_type_2",
    "prise_type_combo_ccs",
    "prise_type_chademo",
    "prise_type_autre",
    "paiement_acte",
    "paiement_autre",
    "reservation",
    "accessibilite_pmr",
    "restriction_gabarit",
    "date_maj",
    "last_modified",
]
controles = [
    "index - id_pdc_itinerance",
    "contact_operateur - id_station_itinerance",
    "nom_enseigne - id_station_itinerance",
    "coordonneesXY - id_station_itinerance",
    "id_station_itinerance - id_pdc_itinerance",
    "nom_station - id_station_itinerance",
    "implantation_station - id_station_itinerance",
    "nbre_pdc - id_station_itinerance",
    "condition_acces - id_station_itinerance",
    "horaires - id_station_itinerance",
    "station_deux_roues - id_station_itinerance",
    "adresse_station - coordonneesXY",
]
origine = "datagouv_organization_or_owner"

-----------------------
## 3 - Séparation des pdc itinerance et hors itinerance
- 0.14 % des points de recharge sont hors itinerance (1 % en 2024)

In [56]:
# séparation des données
data = irve
data[["id_station_itinerance", "id_pdc_itinerance", "restriction_gabarit"]] = data[
    ["id_station_itinerance", "id_pdc_itinerance", "restriction_gabarit"]
].astype("string")
if "last_modified" not in data.columns:
    data["last_modified"] = data["date_maj"]
# data[['last_modified','date_maj']] = data[['last_modified','date_maj']].astype('datetime64')
data["non_concerne"] = data["id_station_itinerance"].str.contains("oncern") | data[
    "id_pdc_itinerance"
].str.contains("oncern")

non_concerne = data[data["non_concerne"]].reset_index()["index"]
itinerance = data[~data["non_concerne"]].reset_index()
itinerance_init = itinerance.loc[:, relations]
log["pdc_hors_itinerance"] = len(non_concerne)
log["pdc_en_itinerance"] = len(itinerance)
print(
    "nombre de pdc hors itinerance : ",
    log["pdc_hors_itinerance"],
    "soit : ",
    len(non_concerne) / (len(non_concerne) + len(itinerance)),
)
print("nombre de pdc en itinerance   : ", log["pdc_en_itinerance"])

nombre de pdc hors itinerance :  383 soit :  0.0022608675119831882
nombre de pdc en itinerance   :  169021

In [57]:
# arborescence des champs et nombre de valeurs différentes
print(itinerance_init.npd.analysis().tree())

-1: root-derived (169021)
   0 : index (0 - 169021)
   12: id_pdc_itinerance (2 - 169019)
      1 : contact_operateur (168770 - 249)
      2 : nom_enseigne (162820 - 6199)
      3 : coordonneesXY (130208 - 38811)
      4 : adresse_station (129070 - 39949)
      5 : id_station_itineranc (119630 - 49389)
      6 : nom_station (128035 - 40984)
      7 : implantation_station (169014 - 5)
      8 : nbre_pdc (168907 - 112)
      9 : condition_acces (169017 - 2)
      10: horaires (167706 - 1313)
      11: station_deux_roues (169017 - 2)
      13: date_maj (167955 - 1064)
         14: last_modified (0 - 1064)
      15: datagouv_organizatio (168869 - 150)

-----------------------
## 4 - Bilan initial intégrité
- 58 % des lignes présentent un défaut d'intégrité (moins de 20% en 2024)
- 9 % avec le nouveau fichier transport

In [58]:
# séparation données bonnes (itinerance_ok_1) et données résiduelles (itinerance_1)
res = analyse_integrite(itinerance_init, schema)
itinerance_ok_1 = itinerance_init.loc[itinerance_init.ok, relations].reset_index(
    drop=True
)
itinerance_1 = itinerance_init.loc[~itinerance_init.ok, relations].reset_index(
    drop=True
)
itinerance_init = itinerance_init.loc[:, relations]
log["init_ok"] = len(itinerance_ok_1)
log["init_ko"] = len(itinerance_1)
print("\nnombre d'enregistrements sans erreurs : ", log["init_ok"])
print("nombre d'enregistrements avec au moins une erreur : ", log["init_ko"])
print("taux d'erreur : ", round(log["init_ko"] / log["pdc_en_itinerance"] * 100), " %")

index - id_pdc_itinerance                              4
contact_operateur - id_station_itinerance           1101
nom_enseigne - id_station_itinerance                5154
coordonneesXY - id_station_itinerance               1910
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                  998
implantation_station - id_station_itinerance        1136
nbre_pdc - id_station_itinerance                    5905
condition_acces - id_station_itinerance               85
horaires - id_station_itinerance                     486
station_deux_roues - id_station_itinerance           297
adresse_station - coordonneesXY                    13130

nombre d'enregistrements sans erreurs :  153353
nombre d'enregistrements avec au moins une erreur :  15668
taux d'erreur :  9  %

-----------------------
## 5 - Séparation doublons pdc - date de maj
- 51 % des pdc en erreur sont liées aux doublons de pdc (40 % fin 2024)
- la suppression des doublons permet de réduire de 94% le nombre de lignes erronnées (50 % fin 2024)

- présence uniquement de 2 doublons avec le nouveau fichier transport

In [59]:
# séparation doublons pdc (doublons_pdc) et données résiduelles (itinerance_2)
itinerance_1["doublons_pdc"] = itinerance_1.sort_values(
    by=["date_maj", "last_modified"]
).duplicated("id_pdc_itinerance", keep="last")

doublons_pdc = (
    itinerance_1[itinerance_1["doublons_pdc"]]
    .loc[:, relations]
    .reset_index(drop=True)["index"]
)
# doublons_pdc = itinerance_1[itinerance_1['doublons_pdc']].loc[:, relations].reset_index(drop=True)
itinerance_2 = (
    itinerance_1[~itinerance_1["doublons_pdc"]].loc[:, relations].reset_index(drop=True)
)
itinerance_1 = itinerance_1.loc[:, relations]
log["doublons_pdc"] = len(doublons_pdc)
log["sans_doublons_pdc"] = len(itinerance_2)
print(
    "nombre de doublons pdc : ",
    log["doublons_pdc"],
    " soit ",
    round(log["doublons_pdc"] / log["init_ko"] * 100),
    " %",
)
print(
    "nombre de pdc sans doublon   : ",
    log["sans_doublons_pdc"],
    " soit ",
    round(log["sans_doublons_pdc"] / log["init_ko"] * 100),
    " %",
)

nombre de doublons pdc :  2  soit  0  %
nombre de pdc sans doublon   :  15666  soit  100  %

In [60]:
# séparation données bonnes (itinerance_ok_3) et données résiduelles (itinerance_3)
res = analyse_integrite(itinerance_2, schema)
itinerance_ok_3 = itinerance_2.loc[itinerance_2.ok, relations].reset_index(drop=True)
itinerance_3 = itinerance_2.loc[~itinerance_2.ok, relations].reset_index(drop=True)
itinerance_2 = itinerance_2.loc[:, relations]
log["etape3_ok"] = len(itinerance_ok_3)
log["etape3_ko"] = len(itinerance_3)
print("\nnombre d'enregistrements sans erreurs : ", log["etape3_ok"])
print("nombre d'enregistrements avec au moins une erreur : ", log["etape3_ko"])

index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance           1101
nom_enseigne - id_station_itinerance                5154
coordonneesXY - id_station_itinerance               1910
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                  998
implantation_station - id_station_itinerance        1136
nbre_pdc - id_station_itinerance                    5905
condition_acces - id_station_itinerance               85
horaires - id_station_itinerance                     486
station_deux_roues - id_station_itinerance           297
adresse_station - coordonneesXY                    13130

nombre d'enregistrements sans erreurs :  2
nombre d'enregistrements avec au moins une erreur :  15664

-----------------------
## 6 - Séparation doublons station - date de maj
- la suppression des anciens pdc permet de réduire de 13 % supplémentaire le nombre de lignes erronnées
- les dernières erreurs correspondent à des stations associées à 69 opérateurs et sont liées à des causes multiples

In [61]:
# séparation doublons stations (doublons_stat_maj) et données résiduelles (itinerance_4)
itinerance_3["stat_maj"] = itinerance_3.id_station_itinerance + itinerance_3.date_maj
stat_maj_unique = itinerance_3.sort_values(by="stat_maj").drop_duplicates(
    "id_station_itinerance", keep="last"
)
itinerance_3["last_stat_maj"] = itinerance_3["stat_maj"].isin(
    stat_maj_unique["stat_maj"]
)

doublons_stat_maj = (
    itinerance_3[~itinerance_3["last_stat_maj"]]
    .loc[:, relations]
    .reset_index(drop=True)["index"]
)
itinerance_4 = (
    itinerance_3[itinerance_3["last_stat_maj"]].loc[:, relations].reset_index(drop=True)
)
itinerance_3 = itinerance_3.loc[:, relations]
log["doublons_station"] = len(doublons_stat_maj)
log["sans_doublons_station"] = len(itinerance_4)
print(
    "nombre de doublons stations : ",
    log["doublons_station"],
    " soit ",
    round(log["doublons_station"] / log["init_ko"] * 100),
    " %",
)
print("nombre de pdc sans doublon   : ", log["sans_doublons_station"])

nombre de doublons stations :  695  soit  4  %
nombre de pdc sans doublon   :  14969

In [62]:
# séparation données bonnes (itinerance_ok_5) et données résiduelles (itinerance_5 / itinerance_5_full)
res = analyse_integrite(itinerance_4, schema)
itinerance_ok_5 = itinerance_4.loc[itinerance_4.ok, relations].reset_index(drop=True)
itinerance_5_full = itinerance_4.loc[~itinerance_4.ok].reset_index(drop=True)
itinerance_5 = itinerance_5_full.loc[:, relations]
# itinerance_4 = itinerance_4.loc[:, relations]
log["etape5_ok"] = len(itinerance_ok_5)
log["etape5_ko"] = len(itinerance_5)
print("\nnombre d'enregistrements sans erreurs : ", log["etape5_ok"])
print(
    "nombre d'enregistrements avec au moins une erreur : ",
    log["etape5_ko"],
    " soit ",
    round(log["etape5_ko"] / log["etape3_ko"] * 100),
    " %",
)

index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              2
nom_enseigne - id_station_itinerance                4100
coordonneesXY - id_station_itinerance               1009
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                  497
implantation_station - id_station_itinerance         130
nbre_pdc - id_station_itinerance                    4496
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                     112
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                    12582

nombre d'enregistrements sans erreurs :  1012
nombre d'enregistrements avec au moins une erreur :  13957  soit  89  %

In [63]:
# structure des données présentant une erreur et nombre de valeurs
print(itinerance_5.npd.analysis().tree())

-1: root-derived (13957)
   0 : index (0 - 13957)
   1 : contact_operateur (13860 - 97)
   2 : nom_enseigne (12535 - 1422)
   3 : coordonneesXY (11392 - 2565)
   4 : adresse_station (9348 - 4609)
   5 : id_station_itineranc (10058 - 3899)
      9 : condition_acces (3897 - 2)
      11: station_deux_roues (3897 - 2)
      13: date_maj (3571 - 328)
         14: last_modified (0 - 328)
   6 : nom_station (10631 - 3326)
   7 : implantation_station (13952 - 5)
   8 : nbre_pdc (13909 - 48)
   10: horaires (13795 - 162)
   12: id_pdc_itinerance (0 - 13957)
   15: datagouv_organizatio (13894 - 63)

In [64]:
# nb maxi d'erreurs
itinerance_4["somme"] = 0
for name in res.keys():
    itinerance_4["somme"] += 1 - itinerance_4[name]
erreurs = max(itinerance_4["somme"])
maxi = itinerance_4[itinerance_4.somme >= erreurs]
print("nombre d'enregistrements avec ", erreurs, " erreurs : ", len(maxi))

nombre d'enregistrements avec  5  erreurs :  1

In [65]:
# principaux opérateurs contributeur de défauts
operateurs = list(
    itinerance_5.drop_duplicates("contact_operateur")["contact_operateur"]
)
erreurs_op = [
    len(itinerance_5.loc[itinerance_5.contact_operateur == operateur])
    for operateur in operateurs
]
err_op_5, oper_5 = tuple(zip(*(sorted(zip(erreurs_op, operateurs), reverse=True))[:5]))
err_op_10, oper_10 = tuple(
    zip(*(sorted(zip(erreurs_op, operateurs), reverse=True))[:10])
)

print(
    len(err_op_5),
    " opérateurs représentent : ",
    round(sum(err_op_5) / sum(erreurs_op) * 100),
    " % des écarts\n",
)
for err, op in zip(err_op_5, oper_5):
    print(err, op)

5  opérateurs représentent :  60  % des écarts

4496 sav@izivia.com
1396 supervision-ev.france@totalenergies.com
1139 support@alizecharge.fr
819 info@ionity.eu
470 contact@qovoltis.com

In [66]:
print(
    len(err_op_10),
    " opérateurs représentent : ",
    round(sum(err_op_10) / sum(erreurs_op) * 100),
    " % des écarts\n",
)
for err, op in zip(err_op_10, oper_10):
    print(err, op)

10  opérateurs représentent :  73  % des écarts

4496 sav@izivia.com
1396 supervision-ev.france@totalenergies.com
1139 support@alizecharge.fr
819 info@ionity.eu
470 contact@qovoltis.com
462 assistance-technique@ouestcharge-paysdelaloire-moncompte.fr
437 roaming@zunder.com
401 fabien.lepeytre@allego.eu
276 kg@lastmilesolutions.com
250 bornes@lidl.fr

-----------------------
## 7 - Synthèse

### fichiers
Génération des fichiers intégrant les défauts d'intégrité :
- fichier csv des lignes résiduelles à traiter (IRVE_itinerance_residuel)
- fichier csv des données itinerance avec indicateur des données à corriger ou à ignorer (IRVE_itinerance_complet)
- fichier csv des données itinerance valides (IRVE_itinerance_valide)
- fichier csv des doublons (IRVE_itinerance_doublons)

In [67]:
# consolidation des données
itinerance["doublons_stat_maj"] = itinerance["index"].isin(doublons_stat_maj)
itinerance["doublons_pdc"] = itinerance["index"].isin(doublons_pdc)
itinerance["lignes_a_corriger"] = itinerance["index"].isin(itinerance_5["index"])
itinerance["doublons_a_supprimer"] = (
    itinerance["doublons_stat_maj"] | itinerance["doublons_pdc"]
)
itinerance["lignes_ko"] = (
    itinerance["doublons_a_supprimer"] | itinerance["lignes_a_corriger"]
)
print("total des lignes à corriger : ", itinerance["lignes_a_corriger"].sum())
itinerance_doublons = itinerance[itinerance["doublons_a_supprimer"]].reset_index(
    drop=True
)
print("total des doublons à supprimer : ", len(itinerance_doublons))
itinerance_ok = itinerance[~itinerance["lignes_ko"]].reset_index(drop=True)
print("nombre de pdc avec controles ok : ", len(itinerance_ok))

total des lignes à corriger :  13957
total des doublons à supprimer :  697
nombre de pdc avec controles ok :  154367

In [68]:
# génération des fichiers
extension = log["date_irve"] + ".csv"
itinerance_5_full.to_csv("IRVE_itinerance_residuel" + extension)
itinerance.to_csv("IRVE_itinerance_complet" + extension)
itinerance_ok.to_csv("IRVE_itinerance_valide" + extension)
itinerance_doublons.to_csv("IRVE_itinerance_doublons" + extension)
log["IRVE_itinerance_residuel" + extension] = len(itinerance_5_full)
log["IRVE_itinerance_complet" + extension] = len(itinerance)
log["IRVE_itinerance_valide" + extension] = len(itinerance_ok)
log["IRVE_itinerance_valide_stat" + extension] = len(
    itinerance_ok.drop_duplicates("id_station_itinerance", keep="last")
)
log["IRVE_itinerance_doublons" + extension] = len(itinerance_doublons)

In [69]:
l_prefix = list(
    pd.read_csv(
        log["chemin"] + "/" + "Operations_Recharge_16-07-2024.csv",
        sep=";",
        low_memory=False,
        dtype="object",
    )["Identifiant"]
)
l_prefix[0]

'FR073'

In [70]:
for op in oper_5:
    print("IRVE_itinerance_residuel" + "_" + op + "_" + extension)
    itinerance_5_full.loc[itinerance_5_full.contact_operateur == op].to_csv(
        "IRVE_itinerance_residuel" + "_" + op + "_" + extension
    )

IRVE_itinerance_residuel_sav@izivia.com_2026-09-29.csv
IRVE_itinerance_residuel_supervision-ev.france@totalenergies.com_2026-09-29.csv
IRVE_itinerance_residuel_support@alizecharge.fr_2026-09-29.csv
IRVE_itinerance_residuel_info@ionity.eu_2026-09-29.csv
IRVE_itinerance_residuel_contact@qovoltis.com_2026-09-29.csv

### vérification de l'intégrité

In [71]:
# vérification de l'absence d'erreurs
res = analyse_integrite(itinerance_ok.loc[:, relations], schema, affiche=False)
log["bilan_erreurs"] = sum(res.values())
log["date"] = datetime.now().isoformat()
print("bilan intégrité :")
print("    erreurs : ", log["bilan_erreurs"])

bilan intégrité :
    erreurs :  0

In [72]:
# structure des données bonnes
# print(Cdataset(itinerance_ok.loc[:, mandatory]).tree())
print(itinerance_ok.loc[:, mandatory].npd.analysis().tree())

-1: root-derived (154367)
   4 : id_station_itineranc (108877 - 45490)
      0 : contact_operateur (45250 - 240)
      1 : nom_enseigne (40609 - 4881)
      2 : coordonneesXY (9276 - 36214)
         3 : adresse_station (833 - 35381)
      5 : nom_station (7828 - 37662)
      6 : implantation_station (45485 - 5)
      7 : nbre_pdc (45385 - 105)
      8 : condition_acces (45488 - 2)
      9 : horaires (44302 - 1188)
      10: station_deux_roues (45488 - 2)
   11: id_pdc_itinerance (0 - 154367)
   12: puissance_nominale (154126 - 241)
   13: prise_type_ef (154365 - 2)
   14: prise_type_2 (154365 - 2)
   15: prise_type_combo_ccs (154365 - 2)
   16: prise_type_chademo (154365 - 2)
   17: prise_type_autre (154365 - 2)
   18: paiement_acte (154365 - 2)
   19: paiement_autre (154364 - 3)
   20: reservation (154365 - 2)
   21: accessibilite_pmr (154363 - 4)
   22: restriction_gabarit (154210 - 157)
   23: date_maj (153355 - 1012)
      24: last_modified (0 - 1012)

### Structure des données valides

In [81]:
quali = "QualiCharge"
print(
    len(itinerance[itinerance[origine] == quali]),
    len(itinerance_1[itinerance_1[origine] == quali]),
    len(itinerance_2[itinerance_2[origine] == quali]),
    len(itinerance_3[itinerance_3[origine] == quali]),
    len(itinerance_4[itinerance_4[origine] == quali]),
    len(itinerance_5[itinerance_5[origine] == quali]),
)

78726 6372 6372 6372 6295 5484

In [ ]:
stat_ok = (
    itinerance_ok.groupby(origine)
    .agg(nb_pdcs=NamedAgg("id_pdc_itinerance", "count"))
    .reset_index()
)
print(
    len(itinerance_ok),
    len(itinerance[itinerance[origine] == "QualiCharge"]),
    len(itinerance_ok[itinerance_ok[origine] == "QualiCharge"]),
)
stat_ok.sort_values(by="nb_pdcs", ascending=False)[0:30]

154367 78726 73165

                        datagouv_organization_or_owner  nb_pdcs
86                                         QualiCharge    73165
42                                              GIREVE    25454
8                                                Alizé    10432
56                                              IZIVIA    10004
57                                        Indigo Group     7525
26                                             Driveco     3595
3                                                 ALDI     2952
85                                            Qovoltis     2898
36                                        Eco-Movement     2837
38                                Electric 55 Charging     1955
33                                         EV CARS SAS     1643
136                         evzen (SMEG Développement)     1275
125                                            ZE-WATT      880
92                                      Rossini Energy      822
103                                           SOREGIES      679
21           Citeos Ingénierie IdF & Est (Cogelum IdF)      637
120                     TotalEnergies Marketing France      615
113           Syndicat Départemental d'Energie du Tarn      512
71                                            NEXTENEO      451
67                            Mobilize Power Solutions      410
64                                                Lidl      398
114         Syndicat Départemental d'Energies du Rhône      366
5                                               ALLEGO      351
129                                            ZEborne      326
69                                   Métropole de Lyon      317
98                                      SGA Industries      313
76                                    PARTAGE MA BORNE      311
75                                              Ozecar      269
116  Syndicat Intercommunal de l'Electricite et du ...      247
97                                              SEVDEC      226

### Indicateurs

In [25]:
# génération des indicateurs liés aux règles
regles = [
    "Pdc non unique",
    "Station multi-operateurs",
    "Station multi-enseignes",
    "Station multi-localisations",
    "Pdc multi-stations",
    "station avec plusieurs noms",
    "station multi-implantations",
    "nombre de pdc par station incoherent",
    "station multi-acces",
    "station multi-horaires",
    "acces deux-roues incoherent",
    "localisation multi-adresses",
]
principal = [16, 17, 18, 19, 20]
secondaire = [21, 22, 23, 24, 25, 26, 27]
irve = itinerance_5_full  # residuel
total = len(irve)
indic = {}

irve["principal"] = True
for ind in principal:
    irve["principal"] &= irve.iloc[:, ind]
    indic[regles[ind - 16]] = int(total - irve.iloc[:, ind].sum())
irve["secondaire"] = True
for ind in secondaire:
    irve["secondaire"] &= irve.iloc[:, ind]
    indic[regles[ind - 16]] = int(total - irve.iloc[:, ind].sum())
irve["secondaire"] |= ~irve["principal"] & ~irve["secondaire"]
irve["verif"] = irve["principal"] & irve["secondaire"]
indic["principal pdc"] = int(total - irve["principal"].sum())
indic["secondaire pdc"] = int(total - irve["secondaire"].sum())

irve_p = (
    irve[~irve["principal"]]
    .drop_duplicates("id_station_itinerance")
    .reset_index(drop=True)
)
irve_s = (
    irve[~irve["secondaire"]]
    .drop_duplicates("id_station_itinerance")
    .reset_index(drop=True)
)
indic["principal stat"] = len(irve_p)
indic["secondaire stat"] = len(irve_s)

In [26]:
# ajout des principaux opérateurs contributeur de défauts
indic["operateurs"] = list(oper_5)
indic["erreurs_operateurs"] = list(err_op_5)

In [27]:
# ajout de l'indicateur d'écart entre nombre de pdc calculés et saisis
add_nbre_pdc(irve, affiche=True)
indic["nb_pdc_calc-nbre_pdc"] = int(irve["calc-nbre"].sum())

nbre_pdc_ko           4947
35  %

In [28]:
# indicateur d'écart entre nombre de pdc calculés et saisis sur les données sans doublon
itinerance_sans_doublons = itinerance[~itinerance["doublons_a_supprimer"]].reset_index(
    drop=True
)
add_nbre_pdc(itinerance_sans_doublons, affiche=True)

nbre_pdc_ko          31752
19  %

In [29]:
len(itinerance_4)

14969

In [30]:
# stockage des indicateurs
log |= indic
log_file = log["chemin"] + "/" + "logfile.txt"
# with open('logfile.txt', 'a', encoding="utf-8") as f:
with open(log_file, "a", encoding="utf-8") as f:
    f.write(json.dumps(log) + "\n")

In [31]:
itinerance_5_full.columns[16:28]

Index(['index - id_pdc_itinerance',
       'contact_operateur - id_station_itinerance',
       'nom_enseigne - id_station_itinerance',
       'coordonneesXY - id_station_itinerance',
       'id_station_itinerance - id_pdc_itinerance',
       'nom_station - id_station_itinerance',
       'implantation_station - id_station_itinerance',
       'nbre_pdc - id_station_itinerance',
       'condition_acces - id_station_itinerance',
       'horaires - id_station_itinerance',
       'station_deux_roues - id_station_itinerance',
       'adresse_station - coordonneesXY'],
      dtype='object')

-----------------------
## 8 - Exemples d'erreurs résiduelles 

### Erreurs multiples 
- exemple avec le nombre maximal d'erreurs (4) (35 pdc)
- exemple station 'FRS35P35093001B1' avec 25 pdc : coordonnées XY, nom_station, implantation station, condition accès)

In [32]:
maxi.loc[:, relations]

,index,contact_operateur,nom_enseigne,coordonneesXY,adresse_station,id_station_itinerance,nom_station,implantation_station,nbre_pdc,condition_acces,horaires,station_deux_roues,id_pdc_itinerance,date_maj,last_modified
6722,70732,support@mobilize-ps.fr,BODEMER - SCAUTO BAYEUX,"[-1.54360, 47.15431]","16 Bd Sadi Carnot, 14400 Bayeux",FRMBZESMYQC,Scauto Bayeux,Parking privé à usage public,1,Accès libre,"Mo-Fr 07:30-12:00,Mo-Fr 14:00-19:00",false,FRMBZESMYQC1,2024-06-03,2024-06-03

In [33]:
itinerance_4.loc[itinerance_4.id_station_itinerance == "FRS35P35093001B1", relations]

Empty DataFrame
Columns: [index, contact_operateur, nom_enseigne, coordonneesXY, adresse_station, id_station_itinerance, nom_station, implantation_station, nbre_pdc, condition_acces, horaires, station_deux_roues, id_pdc_itinerance, date_maj, last_modified]
Index: []

### Repartition des defauts par operateur
Répartition pour les 10 opérateurs présentant le plus de défauts

In [34]:
print("PdC avec une incohérence : ")
for operateur in oper_10:
    print("\n", sum(itinerance_5.contact_operateur == operateur))
    print("Répartition des incohérences ", operateur, " :")
    for cont in controles:
        # print(cont, sum((itinerance_4['contact_operateur'] == 'supervision-ev.france@totalenergies.com') & ~(itinerance_4[cont])))
        print(
            "{:<50} {:>5}".format(
                cont,
                sum(
                    (itinerance_4["contact_operateur"] == operateur)
                    & ~(itinerance_4[cont])
                ),
            )
        )

PdC avec une incohérence :

 4496
Répartition des incohérences  sav@izivia.com  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                4087
coordonneesXY - id_station_itinerance                392
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                   83
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                    4125
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                     4104

 1396
Répartition des incohérences  supervision-ev.france@totalenergies.com  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   6
coordonneesXY - id_station_itinerance                 22
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                   22
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                      26
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                     1344

 1139
Répartition des incohérences  support@alizecharge.fr  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  0
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    0
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                     1139

 819
Répartition des incohérences  info@ionity.eu  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  0
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    0
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                      819

 470
Répartition des incohérences  contact@qovoltis.com  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  0
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    0
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                      470

 462
Répartition des incohérences  assistance-technique@ouestcharge-paysdelaloire-moncompte.fr  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  0
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    0
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                      462

 437
Répartition des incohérences  roaming@zunder.com  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  0
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    0
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                      437

 401
Répartition des incohérences  fabien.lepeytre@allego.eu  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                 43
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    7
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                       7
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                      394

 276
Répartition des incohérences  kg@lastmilesolutions.com  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                  0
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                    0
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                       0
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                       0
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                      276

 250
Répartition des incohérences  bornes@lidl.fr  :
index - id_pdc_itinerance                              0
contact_operateur - id_station_itinerance              0
nom_enseigne - id_station_itinerance                   0
coordonneesXY - id_station_itinerance                248
id_station_itinerance - id_pdc_itinerance              0
nom_station - id_station_itinerance                   96
implantation_station - id_station_itinerance           0
nbre_pdc - id_station_itinerance                      64
condition_acces - id_station_itinerance                0
horaires - id_station_itinerance                      18
station_deux_roues - id_station_itinerance             0
adresse_station - coordonneesXY                        0

### Defauts operateur ALIZECHARGE
Les défauts identifiés concernent des stations utilisant un même identifiant. Par exemple, la station 'FRADPE77294001' contient 40 points de recharge avec plusieurs adresses, plusieurs localisations, plusieurs noms de station et un nombre de points de rechage variable.

In [ ]:
itinerance_4.loc[
    (~itinerance_4["nom_station - id_station_itinerance"])
    & (itinerance_4["contact_operateur"] == "support@alizecharge.fr"),
    relations,
]

In [ ]:
itinerance_4.loc[
    (~itinerance_4["nbre_pdc - id_station_itinerance"])
    & (itinerance_4["contact_operateur"] == "support@alizecharge.fr"),
    relations,
]

In [ ]:
itinerance_4.loc[itinerance_4.id_station_itinerance == "FRADPE77294001", relations]

In [ ]:
itinerance_4.loc[itinerance_4.coordonneesXY == "[2.969121,48.282539]", relations]

### Defauts operateur LIDL
Les défauts identifiés concernent principalement l'affectation de coordonnées au point de recharge et non à la station. Par exemple, pour une station composée de quatre bornes de deux points de recharge, on trouve une coordonnée différente pour chacune des bornes.

In [ ]:
itinerance_4.loc[
    (~itinerance_4["coordonneesXY - id_station_itinerance"])
    & (itinerance_4["contact_operateur"] == "bornes@lidl.fr"),
    relations,
].sort_values(by=["id_station_itinerance"])[0:50]

### Defauts operateur IZIVIA
Les défauts au nombre de 330 sont liés à une incohérence entre adresse et coordonnées (une même coordonnée a plusieurs adresses différentes). Ce défaut est lié soit à des erreurs de saisie, soit à des ajouts (ou remplacements) ultérieurs de stations à une même localisation.

Les stations Izivia en erreur ont un id_station_itinerance identique à l'id_pdc_itinerance, ce qui se traduit par des adresses multiples pour une même coordonnée.

Par exemple, sur un parking [-0.530598, 47.398424], on trouve 17 stations avec la même coordonnée, le même identifiant entre point de recharge et station et un nombre de PdC indiqué entre 1 et 3.

In [ ]:
itinerance_4.loc[itinerance_4["contact_operateur"] == "sav@izivia.com", relations]

In [ ]:
itinerance_4.loc[
    (~itinerance_4["adresse_station - coordonneesXY"])
    & (itinerance_4["contact_operateur"] == "sav@izivia.com"),
    relations,
].sort_values(by=["coordonneesXY"])[0:50]

In [ ]:
itinerance_4.loc[itinerance_4.coordonneesXY == "[-0.530598, 47.398424]", relations]

### Defauts operateur ENIplenitude
Les défauts (200 points de recharge) sont liés à une erreur de doumentation de l'implantation incohérence entre adresse et coordonnées (une même coordonnée a plusieurs adresses différentes). Ce défaut est lié soit à des erreurs de saisie, soit à des ajouts (ou remplacements) ultérieurs de stations à une même localisation.

Les stations Ionity en erreur ont un id_station_itinerance identique à l'id_pdc_itinerance ainsi qu'un ancien pdc de regroupement par station avec un nom d'enseigne différent (IONITY GMBH), ce qui se traduit par des adresses multiples pour une même coordonnée.

Par exemple, sur l'aire de Mornas [4.732409, 44.194832], on trouve 26 stations avec la même coordonnée, le même identifiant entre point de recharge et station et un nombre de PdC indiqué de 23 pour chaque station.

In [ ]:
itinerance_4.loc[
    itinerance_4["contact_operateur"] == "support@service.emob.eniplenitude.com",
    relations,
]

In [ ]:
itinerance_4.loc[itinerance_4.id_station_itinerance == "FRPLNEH002131", relations]

### Defauts operateur MOBILIZE
Les défauts (350 points de recharge) sont liés à une erreur de doumentation de l'implantation incohérence entre adresse et coordonnées (une même coordonnée a plusieurs adresses différentes). Ce défaut est lié soit à des erreurs de saisie, soit à des ajouts (ou remplacements) ultérieurs de stations à une même localisation.

In [ ]:
itinerance_4.loc[
    itinerance_4["contact_operateur"] == "fastcharge.exploitation@mobilize.com",
    relations,
]

In [ ]:
itinerance_4.loc[itinerance_4.id_station_itinerance == "FRMFCEALBERTVILLE", relations]

### Cohérence implantation_station - id_station
- 107 pdc sont liés à une erreur de choix d'implantation (couplé à d'autres erreurs)

In [ ]:
itinerance_4.loc[
    ~itinerance_4["implantation_station - id_station_itinerance"], relations
]

### Cohérence nom_station - id_station
- 210 pdc sont associés à une station avec un nom non cohérent

In [ ]:
itinerance_4.loc[~itinerance_4["nom_station - id_station_itinerance"], relations]

### Coherence adresse - coordonnees
- 2337 pdc ont une adresse non cohérente avec les coordonnées géographiques

In [ ]:
itinerance_4.loc[~itinerance_4["adresse_station - coordonneesXY"], relations]

In [ ]:
itinerance_4.loc[itinerance_4.coordonneesXY == "[5.2592028, 46.1746523]", relations]

In [ ]:
itinerance_4.loc[
    itinerance_4.adresse_station == "RN 75 ZI DE NOIREFONTAINE 01250 Montagnat",
    relations,
]

In [ ]:
itinerance_4.loc[
    itinerance_4.adresse_station == " RN 75 ZI DE NOIREFONTAINE 01250 Montagnat",
    relations,
]

### Cohérence station - coordonnées
- 218 pdc sont associés à des stations avec plusieurs coordonnées (majorité AlizeCharge)

In [ ]:
itinerance_4.loc[~itinerance_4["coordonneesXY - id_station_itinerance"], relations]

In [ ]:
itinerance_5.loc[itinerance_5.id_station_itinerance == "FRTLSE31555040", relations]

In [ ]:
itinerance_5.loc[itinerance_5.id_station_itinerance == "FRFR1PEHNKRRPQNR", relations]

- exemple : une station avec plusieurs coordonnées -> incompréhension distinction station / pdc

In [ ]:
itinerance_5.loc[itinerance_5.id_station_itinerance == "FR073PCAMAIEUFR", relations]

- exemple : une station avec plusieurs coordonnées -> regroupement de stations ?

In [ ]:
itinerance_5.loc[itinerance_5.id_station_itinerance == "FR55CPBP514", relations]

- exemple : plusieurs stations d'opérateurs différents avec les mêmes coordonnées -> suppression non effectuée lors d'un changement d'opérateur ?

In [ ]:
itinerance_4.loc[itinerance_4.coordonneesXY == "[0.08745032, 48.40887156]", relations]

In [ ]:
itinerance_4.loc[itinerance_4.coordonneesXY == "[-4.374469, 48.471878]", relations]

- exemple : quatre stations avec une localisation identique mais deux adresses différentes + id identique entre station et pdc -> erreur d'adresse et erreur d'id_station ?

In [ ]:
itinerance_5.loc[itinerance_5.coordonneesXY == "[-0.366184, 43.332508]", relations]

### Incoherence nbre_pdc
- 583 pdc ont un champ 'nbre_pdc' mal documenté

In [ ]:
itinerance_4.loc[~itinerance_4["nbre_pdc - id_station_itinerance"], relations][200:215]

### coherence station - enseigne
- 5 stations ont plusieurs noms d'enseigne

In [ ]:
itinerance_4.loc[~itinerance_4["nom_enseigne - id_station_itinerance"], relations]

In [ ]:
itinerance_init.loc[itinerance_init.id_station_itinerance == "FRFR1EAYRU", relations]

In [ ]:
itinerance_init.loc[itinerance_init.nom_enseigne == "RME Loos (FR-FR1)", relations]

### cohérence station - horaires
- exemple de station avec plusieurs types d'horaire (15)

In [ ]:
itinerance_init.loc[itinerance_init.id_station_itinerance == "FRS23D2302001", relations]

### cohérence station - deux-roues
- exemple de station avec plusieurs indications d'accessibilité deux-roues (583)

In [ ]:
itinerance_init.loc[itinerance_init.id_station_itinerance == "FRV75PPX1716", relations]

### stations avec pdc > 350 kW

- exemple de station avec une puissance de plus de 350 kW

In [ ]:
data["p_nom"] = data["puissance_nominale"].str.replace(",", ".")

In [ ]:
data["p_nom"] = data["p_nom"].astype("float")

In [ ]:
from copy import copy

data350 = copy(data.loc[data["p_nom"] > 350, :])

In [ ]:
data350["index"] = 0

In [ ]:
data350.loc[:, relations]

In [ ]:
data350["contact_operateur"].unique()